//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_FLOAT                       163
#define IDB_BITMAP4                     164
#define IDB_NO_FLOAT                    164
#define IDB_PLAYER                      165
#define IDB_PLAYER_DOWN1                167
#define IDB_PLAYER_DOWN2                168
#define IDB_PLAYER_DOWN3                169
#define IDB_PLAYER_DOWN4                170
#define IDB_PLAYER_LEFT1                171
#define IDB_PLAYER_LEFT2                172
#define IDB_PLAYER_LEFT3                173
#define IDB_PLAYER_LEFT4                174
#define IDB_PLAYER_RIGHT1               175
#define IDB_PLAYER_RIGHT2               176
#define IDB_PLAYER_RIGHT3               177
#define IDB_PLAYER_RIGHT4               178
#define IDB_PLAYER_UP1                  179
#define IDB_PLAYER_UP2                  180
#define IDB_PLAYER_UP3                  181
#define IDB_BITMAP3                     182
#define IDB_PLAYER_UP4                  182
#define IDB_BITMAP5                     184
#define IDB_BLACK_ZONE                  184
#define IDB_BITMAP6                     186
#define IDB_BOX                         186
#define IDB_DESSERT                     187
#define IDB_BITMAP7                     188
#define IDB_Obstacle                    189
#define IDB_BITMAP8                     190
#define IDB_MoveIt                      190
#define IDB_DESSERT1                    191
#define IDB_DESSERT2                    192
#define IDB_DESSERT3                    193
#define IDB_DESSERT4                    194
#define IDB_DESSERT5                    195
#define IDB_BACKGROUNDIMAGE             196
#define IDB_BUTTOM                      197
#define IDB_BUTTOM_ENTER                198
#define IDB_BUTTOM_EXIT                 199
#define IDB_BUTTOM_ENTER_HOVER          200
#define IDB_BUTTOM_EXIT_HOVER           201
#define IDB_MONSTER_LEFT1               202
#define IDB_MONSTER_LEFT2               203
#define IDB_MONSTER_LEFT3               204
#define IDB_MONSTER_LEFT4               205
#define IDB_MONSTER_DOWN1               206
#define IDB_MONSTER_DOWN5               206
#define IDB_MONSTER_DOWN2               207
#define IDB_MONSTER_DOWN3               208
#define IDB_MONSTER_DOWN4               209
#define IDB_MONSTER_RIGHT1              210
#define IDB_MONSTER_RIGHT2              211
#define IDB_MONSTER_RIGHT3              212
#define IDB_MONSTER_RIGHT4              213
#define IDB_MONSTER_UP1                 214
#define IDB_MONSTER_UP2                 215
#define IDB_MONSTER_UP3                 216
#define IDB_MONSTER_UP4                 217
#define IDB_HITSHORTLEFT                218
#define IDB_HITSHORTR                   218
#define IDB_HITSHORTL                   219
#define IDB_HITSHORTUP                  220
#define IDB_HITSHORTDown                221
#define IDB_BITMAP9                     222
#define IDB_ROCK                        222
#define IDB_DESSERT_WET                 223
#define IDB_DESSERT_DRY                 224
#define IDB_LAND1                       225
#define IDB_LAND2                       226
#define IDB_LAND3                       227
#define IDB_LAND4                       228
#define IDB_LAND5                       229
#define IDB_LAND_GRASS_DEEP             230
#define IDB_LAND_FLOWER                 231
#define IDB_LAND_GRASS                  232
#define IDB_BUSH1                       233
#define IDB_BUSH2                       234
#define IDB_PIRANHA                     235
#define IDB_WOOD1                       236
#define IDB_WOOD2                       237
#define IDB_ROCK1                       238
#define IDB_POT                         239
#define IDB_SNOW1                       240
#define IDB_SNOW2                       241
#define IDB_SNOW3                       242
#define IDB_SNOW4                       243
#define IDB_SNOW5                       244
#define IDB_SNOWMAN_DOWN1               245
#define IDB_SNOWMAN_DOWN2               246
#define IDB_SNOWMAN_DOWN3               247
#define IDB_SNOWMAN_LEFT1               248
#define IDB_SNOWMAN_LEFT2               249
#define IDB_SNOWMAN_LEFT3               250
#define IDB_SNOWMAN_RIGHT1              251
#define IDB_SNOWMAN_RIGHT2              252
#define IDB_SNOWMAN_RIGHT3              253
#define IDB_SNOWMAN_UP1                 254
#define IDB_SNOWMAN_UP2                 255
#define IDB_SNOWMAN_UP3                 256
#define IDB_CHICKEN_DOWN1               257
#define IDB_CHICKEN_DOWN2               258
#define IDB_CHICKEN_DOWN3               259
#define IDB_CHICKEN_RIGHT1              260
#define IDB_CHICKEN_RIGHT2              261
#define IDB_CHICKEN_RIGHT3              262
#define IDB_CHICKEN_LEFT1               263
#define IDB_CHICKEN_LEFT2               264
#define IDB_CHICKEN_LEFT3               265
#define IDB_CHICKEN_UP1                 266
#define IDB_CHICKEN_UP2                 267
#define IDB_SNOW_BUSH                   268
#define IDB_CHICKEN_UP3                 269
#define IDB_SNOW_POT                    270
#define IDB_SNOW_POT1                   271
#define IDB_SNOW_ROCK                   271
#define IDB_SELECT                      272
#define IDB_BITMAP10                    273
#define IDB_INFO                        273
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        274
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
